INSERT INTO country(country_name) VALUES ('USA');
INSERT INTO country(country_name) VALUES ('Italy');
INSERT INTO country(country_name) VALUES ('Greece');
INSERT INTO country(country_name) VALUES ('North Macedonia');
INSERT INTO country(country_name) VALUES ('Kosovo');
INSERT INTO country(country_name) VALUES ('Montenegro');
INSERT INTO country(country_name) VALUES ('Serbia');
INSERT INTO country(country_name) VALUES ('Bosnia and Hercegovina');
INSERT INTO country(country_name) VALUES ('Bulgaria');
INSERT INTO country(country_name) VALUES ('Romania');
INSERT INTO country(country_name) VALUES ('Turkey');
INSERT INTO country(country_name) VALUES ('Croatia');
INSERT INTO country(country_name) VALUES ('Hungary');
INSERT INTO country(country_name) VALUES ('Austria');
INSERT INTO country(country_name) VALUES ('Germany');
INSERT INTO country(country_name) VALUES ('Slovenia');
INSERT INTO country(country_name) VALUES ('Slovakia');
INSERT INTO country(country_name) VALUES ('Switzerland');
INSERT INTO country(country_name) VALUES ('Spain');
INSERT INTO country(country_name) VALUES ('France');
INSERT INTO country(country_name) VALUES ('United Kingdom');
INSERT INTO country(country_name) VALUES ('Portugal');
INSERT INTO country(country_name) VALUES ('Poland');
INSERT INTO country(country_name) VALUES ('Czechia');
INSERT INTO country(country_name) VALUES ('Denmark');
INSERT INTO country(country_name) VALUES ('Netherlands');
INSERT INTO country(country_name) VALUES ('Albania');